# Comment ignored by the computer
print("Hello")
print("There")
yourname = input("Enter your name: ")
print("Hello There"+ yourname)
print("Did you say your name was", yourname)
answer = input("Yes or No")
if answer == "Yes":print("Alright")
if answer == "No":print("Could you repeat what your name is please?")
if answer == "No":input("What is your name?: ")
feeling = input("How are you (answer good/alright/bad)?: ")
if feeling == "good":print("It is good to hear you are feeling well")
if feeling == "alright":print("I hope your day gets better")
if feeling == "bad":input("Why? What is wrong?: ")
if feeling == "bad":print("there is always tomorrow")
activity = input("What are you going to do today?: ")
print("That sounds interesting")